import type { SectionTypeDef } from "./sections.js";
import {
  ICON_OPTIONS,
  PAYMENT_METHOD_OPTIONS,
  PRODUCT_FIELDS,
  SOCIAL_NETWORKS,
  cta,
  heading,
} from "./vocab.js";

/**
 * E-commerce section types (landing-page building blocks for shops).
 *
 * Mostly presentation sections: prices, discounts and payment methods are
 * content the merchant displays, and buttons point to the merchant's own
 * channels. The exception is a product grid showing the page's linked
 * catalog products — those have live price/stock and go into the cart.
 */
export const COMMERCE_SECTIONS: SectionTypeDef[] = [
  {
    type: "announcement",
    version: 1,
    label: "Announcement bar",
    description: "A slim bar above the header, e.g. nationwide cash on delivery.",
    visual: true,
    fields: [
      { key: "text", type: "text", label: "Announcement", maxLength: 120, required: true, default: "Cash on delivery all over Bangladesh" },
      { key: "icon", type: "select", label: "Icon", options: ICON_OPTIONS, default: "truck" },
      { key: "link", type: "url", label: "Link (optional)" },
      {
        key: "style",
        type: "select",
        label: "Style",
        options: [
          { value: "primary", label: "Primary colour" },
          { value: "accent", label: "Accent colour" },
          { value: "dark", label: "Dark" },
        ],
        default: "dark",
      },
    ],
  },
  {
    type: "shopHeader",
    version: 1,
    label: "Shop header",
    description: "Logo, category links, phone and an order button.",
    visual: true,
    fields: [
      { key: "logo", type: "image", label: "Logo" },
      { key: "brandName", type: "text", label: "Shop name", maxLength: 60, default: "Your Shop" },
      {
        key: "links",
        type: "repeater",
        label: "Menu links",
        itemLabel: "Link",
        maxItems: 6,
        itemFields: [
          { key: "label", type: "text", label: "Label", maxLength: 30, required: true },
          { key: "url", type: "url", label: "Link or #section", required: true },
        ],
      },
      { key: "phone", type: "text", label: "Hotline number", maxLength: 30 },
      cta("cta", "Header button"),
      {
        key: "style",
        type: "select",
        label: "Style",
        options: [
          { value: "bold", label: "Bold" },
          { value: "minimal", label: "Minimal" },
        ],
        default: "bold",
      },
    ],
  },
  {
    type: "promoHero",
    version: 1,
    label: "Promotional hero",
    description: "A large sale banner with offer badge and buttons.",
    visual: true,
    fields: [
      { key: "badge", type: "text", label: "Offer badge", maxLength: 40 },
      { key: "headline", type: "text", label: "Headline", maxLength: 120, required: true, default: "Your favourite products, delivered" },
      { key: "subheadline", type: "textarea", label: "Supporting text", maxLength: 300 },
      cta("primaryCta", "Primary button"),
      cta("secondaryCta", "Secondary button"),
      { key: "image", type: "image", label: "Banner image" },
      { key: "note", type: "text", label: "Small note under the buttons", maxLength: 80 },
      {
        key: "layout",
        type: "select",
        label: "Layout",
        options: [
          { value: "split", label: "Text + image" },
          { value: "banner", label: "Full banner" },
        ],
        default: "split",
      },
    ],
  },
  {
    type: "editorialHero",
    version: 1,
    label: "Editorial hero",
    description: "A calm, magazine-style opening with a large image.",
    visual: true,
    fields: [
      { key: "eyebrow", type: "text", label: "Small label", maxLength: 60 },
      { key: "headline", type: "text", label: "Headline", maxLength: 120, required: true, default: "Crafted for everyday elegance" },
      { key: "subheadline", type: "textarea", label: "Supporting text", maxLength: 300 },
      cta("cta", "Button"),
      { key: "image", type: "image", label: "Image" },
    ],
  },
  {
    type: "categoryGrid",
    version: 1,
    label: "Categories",
    description: "Shop-by-category tiles.",
    visual: true,
    fields: [
      heading("Shop by category"),
      { key: "intro", type: "textarea", label: "Intro", maxLength: 300 },
      {
        key: "style",
        type: "select",
        label: "Style",
        options: [
          { value: "circles", label: "Round icons" },
          { value: "tiles", label: "Large tiles" },
        ],
        default: "circles",
      },
      {
        key: "items",
        type: "repeater",
        label: "Categories",
        itemLabel: "Category",
        minItems: 1,
        maxItems: 8,
        itemFields: [
          { key: "name", type: "text", label: "Name", maxLength: 40, required: true },
          { key: "image", type: "image", label: "Image" },
          { key: "link", type: "url", label: "Link or #section" },
        ],
      },
    ],
  },
  {
    type: "productGrid",
    version: 1,
    label: "Products",
    description: "A grid of product cards with price, discount and button.",
    visual: true,
    fields: [
      heading("Popular products"),
      { key: "intro", type: "textarea", label: "Intro", maxLength: 300 },
      {
        key: "columns",
        type: "select",
        label: "Columns on desktop",
        options: [
          { value: "3", label: "3" },
          { value: "4", label: "4" },
        ],
        default: "4",
      },
      {
        key: "style",
        type: "select",
        label: "Card style",
        options: [
          { value: "cards", label: "Cards" },
          { value: "minimal", label: "Minimal" },
        ],
        default: "cards",
      },
      {
        key: "source",
        type: "select",
        label: "Products shown",
        help: "Your products are the ones linked on the Products tab: live price and stock, and customers can order them. Custom cards are display only.",
        options: [
          { value: "catalog", label: "Your products (Products tab)" },
          { value: "manual", label: "Custom cards (display only)" },
        ],
        default: "catalog",
      },
      {
        key: "items",
        type: "repeater",
        label: "Custom cards",
        help: "Shown when this page has no linked products, or when “Custom cards” is selected above.",
        itemLabel: "Product",
        minItems: 1,
        maxItems: 12,
        itemFields: PRODUCT_FIELDS,
      },
      cta("viewAll", "View-all button"),
    ],
  },
  {
    type: "offerBanner",
    version: 1,
    label: "Offer / flash sale",
    description: "One highlighted offer with old and new price.",
    visual: true,
    fields: [
      { key: "badge", type: "text", label: "Badge", maxLength: 30, default: "Flash sale" },
      heading("Today's offer"),
      { key: "text", type: "textarea", label: "Text", maxLength: 300 },
      { key: "deadline", type: "text", label: "Offer ends (text)", maxLength: 80 },
      { key: "image", type: "image", label: "Image" },
      { key: "price", type: "price", label: "Offer price (BDT)" },
      { key: "oldPrice", type: "price", label: "Previous price (BDT)" },
      cta("cta", "Button"),
      {
        key: "style",
        type: "select",
        label: "Style",
        options: [
          { value: "bold", label: "Bold" },
          { value: "editorial", label: "Editorial" },
        ],
        default: "bold",
      },
    ],
  },
  {
    type: "trustFeatures",
    version: 1,
    label: "Why choose us",
    description: "Short trust points: cash on delivery, fast delivery, easy returns.",
    visual: true,
    fields: [
      heading("", false),
      {
        key: "items",
        type: "repeater",
        label: "Points",
        itemLabel: "Point",
        minItems: 1,
        maxItems: 6,
        itemFields: [
          { key: "icon", type: "select", label: "Icon", options: ICON_OPTIONS, default: "check" },
          { key: "title", type: "text", label: "Title", maxLength: 50, required: true },
          { key: "text", type: "text", label: "Detail", maxLength: 120 },
        ],
      },
      {
        key: "style",
        type: "select",
        label: "Style",
        options: [
          { value: "strip", label: "Compact strip" },
          { value: "cards", label: "Cards" },
        ],
        default: "strip",
      },
    ],
  },
  {
    type: "deliveryInfo",
    version: 1,
    label: "Delivery & payment",
    description: "Delivery areas, time and charge, plus accepted payment methods (display only).",
    visual: true,
    fields: [
      heading("Delivery information"),
      { key: "intro", type: "textarea", label: "Intro", maxLength: 300 },
      {
        key: "zones",
        type: "repeater",
        label: "Delivery areas",
        itemLabel: "Area",
        maxItems: 6,
        itemFields: [
          { key: "area", type: "text", label: "Area", maxLength: 50, required: true },
          { key: "time", type: "text", label: "Delivery time", maxLength: 40 },
          { key: "charge", type: "price", label: "Delivery charge (BDT)" },
        ],
      },
      { key: "paymentHeading", type: "text", label: "Payment heading", maxLength: 60, default: "We accept" },
      {
        key: "payments",
        type: "repeater",
        label: "Payment methods shown",
        help: "Display only — ConfirmX does not process these payments.",
        itemLabel: "Method",
        maxItems: 7,
        itemFields: [{ key: "method", type: "select", label: "Method", options: PAYMENT_METHOD_OPTIONS, default: "cod" }],
      },
      { key: "note", type: "textarea", label: "Note", maxLength: 300 },
    ],
  },
  {
    type: "shopFooter",
    version: 1,
    label: "Shop footer",
    description: "Contact details, links, social profiles and accepted payments.",
    visual: true,
    fields: [
      { key: "brandName", type: "text", label: "Shop name", maxLength: 60, default: "Your Shop" },
      { key: "tagline", type: "text", label: "Tagline", maxLength: 140 },
      { key: "phone", type: "text", label: "Phone", maxLength: 30 },
      { key: "email", type: "text", label: "Email", maxLength: 120 },
      { key: "address", type: "textarea", label: "Address", maxLength: 300 },
      {
        key: "links",
        type: "repeater",
        label: "Links",
        itemLabel: "Link",
        maxItems: 8,
        itemFields: [
          { key: "label", type: "text", label: "Label", maxLength: 40, required: true },
          { key: "url", type: "url", label: "URL", required: true },
        ],
      },
      {
        key: "socials",
        type: "repeater",
        label: "Social profiles",
        itemLabel: "Profile",
        maxItems: 8,
        itemFields: [
          { key: "network", type: "select", label: "Network", options: SOCIAL_NETWORKS, default: "facebook" },
          { key: "url", type: "url", label: "Profile URL", required: true },
        ],
      },
      {
        key: "payments",
        type: "repeater",
        label: "Payment methods shown",
        help: "Display only — ConfirmX does not process these payments.",
        itemLabel: "Method",
        maxItems: 7,
        itemFields: [{ key: "method", type: "select", label: "Method", options: PAYMENT_METHOD_OPTIONS, default: "cod" }],
      },
      { key: "copyright", type: "text", label: "Copyright line", maxLength: 120 },
    ],
  },
];
